# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('sector', models.CharField(choices=[('IT', 'IT'), ('DEVELOPER', 'developer'), ('TESTER', 'tester')], max_length=30)),
                ('salary_range', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='sector',
            field=models.CharField(choices=[('IT', 'IT'), ('DEVELOPER', 'developer'), ('TESTER', 'tester')], max_length=30),
        ),
    ]
