# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0002_auto_20160703_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter',
            field=models.CharField(max_length=30),
        ),
    ]
